**NETFLIX PROJECT**

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importing and reading data file
df = pd.read_csv('/content/drive/MyDrive/Netflix dataset/combined_data_1.txt.zip',header = None, names = ['Cust_Id', 'Rating'], usecols = [0,1])

# converting rating column to a float
df['Rating'] = df['Rating'].astype(float)

In [3]:
df

          Cust_Id  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [4]:
# datatype of columns
df.dtypes

Cust_Id     object
Rating     float64
dtype: object

In [5]:
# Checking all the movie id's present in our data
movie_count = df[df['Cust_Id'].str.contains(':')].count()[0]

/tmp/ipython-input-5-2799160191.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movie_count = df[df['Cust_Id'].str.contains(':')].count()[0]

In [6]:
movie_count

4499

In [7]:
# shape of data
df.shape

(24058263, 2)

In [8]:
df.head()

   Cust_Id  Rating
0       1:     NaN
1  1488844     3.0
2   822109     5.0
3   885013     4.0
4    30878     4.0

In [9]:
# no of unique customer id in our data
cust_count=df['Cust_Id'].nunique()
cust_count

475257

In [10]:
# total cust_count
# In this total customer id count the movid id will be also counted.
cust_count = cust_count-movie_count
cust_count

470758

In [11]:
# total rating
rating_count = df['Rating'].count()
rating_count

24053764

In [12]:
# Segregation of our data
movie_np = []
for x in df['Cust_Id']:
    if ':' in x:
        y = x.replace(':',"")
    movie_np.append(y)

In [13]:
df['MovieID'] = movie_np

In [14]:
df

          Cust_Id  Rating MovieID
0              1:     NaN       1
1         1488844     3.0       1
2          822109     5.0       1
3          885013     4.0       1
4           30878     4.0       1
...           ...     ...     ...
24058258  2591364     2.0    4499
24058259  1791000     2.0    4499
24058260   512536     5.0    4499
24058261   988963     3.0    4499
24058262  1704416     3.0    4499

[24058263 rows x 3 columns]

In [15]:
df.dropna(inplace=True)
df

          Cust_Id  Rating MovieID
1         1488844     3.0       1
2          822109     5.0       1
3          885013     4.0       1
4           30878     4.0       1
5          823519     3.0       1
...           ...     ...     ...
24058258  2591364     2.0    4499
24058259  1791000     2.0    4499
24058260   512536     5.0    4499
24058261   988963     3.0    4499
24058262  1704416     3.0    4499

[24053764 rows x 3 columns]

In [16]:
df['CustID']  = df['Cust_Id'].astype(int)
df['MovieID']  = df['MovieID'].astype(int)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 4 columns):
 #   Column   Dtype
---  ------   -----
 0   Cust_Id  object
 1   Rating   float64
 2   MovieID  int64
 3   CustID   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 917.6+ MB

In [18]:
# filteration
data_cust_summary = df.groupby('CustID')['Rating'].count()
data_cust_summary

CustID
6          153
7          195
8           21
10          49
25           4
          ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62
Name: Rating, Length: 470758, dtype: int64

In [19]:
# customers with more than 36 movie views
movie_benchmark = round(data_cust_summary.quantile(0.60))
movie_benchmark

36

In [20]:
Rejected_cust = data_cust_summary[data_cust_summary<movie_benchmark].index
# When we use groupby fxn the column becomes index
Rejected_cust

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustID', length=282042)

In [21]:
# Filtering our movie data
# First we will get the count of ratings for every movie.
data_movie_summary = df.groupby('MovieID')['Rating'].count()
data_movie_summary

MovieID
1        547
2        145
3       2012
4        142
5       1140
        ...
4495     614
4496    9519
4497     714
4498     269
4499     428
Name: Rating, Length: 4499, dtype: int64

In [22]:
cust_benchmark = round(data_movie_summary.quantile(0.60))
cust_benchmark

908

In [23]:
Rejected_movies = data_movie_summary[data_movie_summary<cust_benchmark].index
Rejected_movies

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='MovieID', length=2699)

In [24]:
# removing rejected data and upload as original
df = df[~df['MovieID'].isin(Rejected_movies)]
df

          Cust_Id  Rating  MovieID   CustID
695       1025579     4.0        3  1025579
696        712664     5.0        3   712664
697       1331154     4.0        3  1331154
698       2632461     3.0        3  2632461
699         44937     5.0        3    44937
...           ...     ...      ...      ...
24056844   267802     4.0     4496   267802
24056845  1559566     3.0     4496  1559566
24056846   293198     3.0     4496   293198
24056847    70814     2.0     4496    70814
24056848  1316220     5.0     4496  1316220

[23218285 rows x 4 columns]

In [25]:
df = df[~df['CustID'].isin(Rejected_cust)]
df

          Cust_Id  Rating  MovieID   CustID
696        712664     5.0        3   712664
697       1331154     4.0        3  1331154
698       2632461     3.0        3  2632461
699         44937     5.0        3    44937
700        656399     4.0        3   656399
...           ...     ...      ...      ...
24056842  1055714     5.0     4496  1055714
24056843  2643029     4.0     4496  2643029
24056844   267802     4.0     4496   267802
24056845  1559566     3.0     4496  1559566
24056846   293198     3.0     4496   293198

[19695836 rows x 4 columns]

In [26]:
df = df.drop(columns=['CustID'])
df

          Cust_Id  Rating  MovieID
696        712664     5.0        3
697       1331154     4.0        3
698       2632461     3.0        3
699         44937     5.0        3
700        656399     4.0        3
...           ...     ...      ...
24056842  1055714     5.0     4496
24056843  2643029     4.0     4496
24056844   267802     4.0     4496
24056845  1559566     3.0     4496
24056846   293198     3.0     4496

[19695836 rows x 3 columns]

In [27]:
from google.colab import files
imported = files.upload()

Saving NetflixMovieData.csv to NetflixMovieData (1).csv

In [28]:
df_title = pd.read_csv('NetflixMovieData.csv',header=None,usecols=[0,1,2],names=['MovieID','Year','Name'])
df_title

       MovieID    Year                                               Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17764    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765    17767  2004.0                  Fidel Castro: American Experience
17766    17768  2000.0                                              Epoch
17767    17769  2003.0                                        The Company
17768    17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [29]:
! pip install Scikit-surprise

Requirement already satisfied: Scikit-surprise in /usr/local/lib/python3.11/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.23.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.15.3)

In [31]:
#! pip install numpy==1.23.5

^C

In [32]:
from surprise import Reader , Dataset , SVD
from surprise.model_selection import cross_validate

In [33]:
reader = Reader()

In [37]:
data = Dataset.load_from_df(df[['Cust_Id','MovieID','Rating']][:1000000],reader)

In [38]:
model = SVD()

In [39]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([0.96933917, 0.97061941, 0.96683578]),
 'fit_time': (23.667214155197144, 25.68604803085327, 25.672253608703613),
 'test_time': (6.248681306838989, 5.542208194732666, 5.851550102233887)}

In [40]:
# recommendation for any particular user for all those movie.
user_1331154 = df_title.copy()

In [41]:
user_1331154['Estimate Score'] = user_1331154['MovieID'].apply(lambda x : model.predict(1331154,x).est)

In [42]:
user_1331154

,MovieID,Year,Name,Estimate Score
0,1,2003.0,Dinosaur Planet,3.672124
1,2,2004.0,Isle of Man TT 2004 Review,3.672124
2,3,1997.0,Character,3.750835
3,4,1994.0,Paula Abdul's Get Up & Dance,3.672124
4,5,2004.0,The Rise and Fall of ECW,3.948777
...,...,...,...,...
17764,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.672124
17765,17767,2004.0,Fidel Castro: American Experience,3.672124
17766,17768,2000.0,Epoch,3.672124
17767,17769,2003.0,The Company,3.672124
17768,17770,2003.0,Alien Hunter,3.672124

In [46]:
user_77 = df_title.copy()

In [47]:
user_77['Estimate Score'] = user_1236['MovieID'].apply(lambda x : model.predict(1236,x).est)
user_77

,MovieID,Year,Name,Estimate Score
0,1,2003.0,Dinosaur Planet,3.672124
1,2,2004.0,Isle of Man TT 2004 Review,3.672124
2,3,1997.0,Character,3.750835
3,4,1994.0,Paula Abdul's Get Up & Dance,3.672124
4,5,2004.0,The Rise and Fall of ECW,3.948777
...,...,...,...,...
17764,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.672124
17765,17767,2004.0,Fidel Castro: American Experience,3.672124
17766,17768,2000.0,Epoch,3.672124
17767,17769,2003.0,The Company,3.672124
17768,17770,2003.0,Alien Hunter,3.672124

In [49]:
# The movies with highest rating will be recommended to the user_77.

user_77.sort_values('Estimate Score',ascending=False)

,MovieID,Year,Name,Estimate Score
269,270,2001.0,Sex and the City: Season 4,4.409849
240,241,1959.0,North by Northwest,4.303321
208,209,1996.0,Star Trek: Deep Space Nine: Season 5,4.264566
31,32,2004.0,ABC Primetime: Mel Gibson's The Passion of the...,4.236189
32,33,2000.0,Aqua Teen Hunger Force: Vol. 1,4.206697
...,...,...,...,...
187,188,2005.0,Dead Birds,2.834123
224,225,2004.0,The Cookout,2.756301
126,127,1987.0,Fatal Beauty,2.703578
94,95,1985.0,Dona Herlinda and Her Son,2.669277
180,181,2004.0,The Last Shot,2.649691